apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: queue-test-repo
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: queue-test-kustomization
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: queue-test-repo
  path: "./kustomize"
  prune: true
  wait: false
  timeout: 5m